# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту govoruchin_nv@mail.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - govoruchin_nv@mail.ru
  on_success: never # default: change
  on_failure: always # default: always
  env:
    global:
      - CODECOV_TOKEN="7bd3f165-7807-4c60-b87a-75263b41ac23"